package com.aboveware.aboveabc80.terminal

object ROMStrings {
    // Strings extracted from 23-054E7.bin
    // English (0), French (1), German (2)

    val stringsEN = arrayOf(
        "Keyboard",
        "Transmit",
        "Receive=",
        "Speed=",
        "Parity",
        "Print,",
        "No Check",
        "No",
        "7 Bits,",
        "8 Bits,",
        "Cursor",
        "Control Mode",
        "Set-Up",
        "Display",
        "Auto Answerback",
        "Characters",
        "Local",
        "Concealed",
        "XOFF",
        "VT",
        "Press,",
        "Data Leads Only",
        "User",
        "Disconnect,",
        "Terminal",
        "Status",
        "Bell",
        "Even",
        "Odd",
        "Line",
        "Scroll",
        "Clear",
        "Directory",
        "80 Columns",
        "132 Columns",
        "Wrap",
        "Jump",
        "Smooth",
        "Light",
        "Dark",
        "Underline",
        "Style",
        "Lock",
        "Indicator",
        "Writable",
        "Unlock",
        "Locked",
        "7-bit",
        "8-bit",
        "Numeric",
        "Application",
        "New Line",
        "UPSS",
        "Supplemental",
        "ISO Latin-1",
        "110",
        "150",
        "192",
        "128",
        "Mark",
        "Space",
        "Echo",
        "RS-232",
        "Modem",
        "60 ms",
        "Unlimited",
        "Limited",
        "Full Page",
        "Only",
        "All",
        "Terminator = FF",
        "Caps",
        "Shift",
        "Auto Repeat",
        "Keyclick",
        "Margin Bell",
        "Warning Bell",
        "Compose",
        "Delete",
        "Backspace",
        "Tab",
        "ENTER",
        "Ready"
    )

    val stringsFR = arrayOf(
        "Clavier",
        "Mode de fonct.",
        "Récep.=",
        "Emiss.=",
        "Imprimante:",
        "7 bits",
        "Vit.=",
        "parité",
        "Touche",
        "8 bits",
        "Sans",
        "modifiables",
        "Affichage",
        "aract -",
        "<FLECHE>",
        "pour vous déplacer",
        "réponse",
        "impaire",
        "paire",
        "00 ID VT",
        "Alarme",
        "Interface",
        "RS-232,0",
        "vérif",
        "français",
        "ctrl auto",
        "élement",
        "Mode",
        "ation",
        "Déconnecté",
        "après",
        "<VALIDER>",
        "pour comm",
        "vers l'OC",
        "Imprim",
        "données seul",
        "XOFF",
        "D.U.",
        "ligne",
        "terminateur",
        "Contrôleur",
        "d'état",
        "des",
        "s e i",
        "quereis",
        "ceralanur.",
        "Con",
        "Écho",
        "comm.",
        "Tab",
        "Rem",
        "Rappel",
        "Sauvegarde",
        "américain",
        "flamand",
        "canadien f",
        "finno",
        "norv",
        "gien",
        "/belge",
        "espagnol",
        "portuga",
        "défaut",
        "Sortie",
        "suiv.",
        "ol. 132",
        "Retour",
        "rapide",
        "lent",
        "norm",
        "Souligné",
        "Bloc",
        "Indicateur",
        "d'attente",
        "320 T",
        "num",
        "applic",
        "sec.",
        "Nelle",
        "UPSS DEC Suppl",
        "UPSS ISO Latin-1",
        "64",
        "128",
        "travail",
        "1 b d'arrêt",
        "2 b d'arrêt",
        "modem",
        "60 ms",
        "lim",
        "Msg",
        "Plein page",
        "Seul",
        "et graph",
        "tout",
        "= Av",
        "1 page",
        "informat",
        "sup. MAJ./min.",
        "0 Bip",
        "marge",
        "Intrupt.",
        "composé",
        "suppr",
        "Backspace",
        "tab.",
        "ESC Annul"
    )

    val stringsDE = arrayOf(
        "Tastatur:",
        "Identif. VT",
        "Senden",
        "Empfang=",
        "Geschwind=",
        "Drücken Sie EINGABE",
        "um diesen,",
        "weiter mit den Pfeiltasten",
        "Parität",
        "keine Prüfung",
        "Keinisch",
        "Schreibmarke",
        "gesperrt",
        "7 Bit, 8 Bit,",
        "Abfallzeit",
        "Antwort",
        "Drucker",
        "eichesichtbar",
        "Statuszeile:",
        "gerade",
        "drucken",
        "bereit",
        "modem (polig)",
        "Bildlauf",
        "XOFF",
        "Auto-Modus",
        "Steuer-Betrieb",
        "Feststellen:",
        "Benutzerauswahl",
        "Französisch",
        "Deutsch",
        "KOMMUNIKATION",
        "Stoppb.",
        "Trennen",
        "Hostrechner",
        "Randsignal",
        "Normal",
        "ALLGEMEINES (Schweiz)",
        "ÜBERSICHT",
        "klick",
        "Typamatik",
        "Auswahlbild",
        "Anwendung",
        "ANZEIGE",
        "DRUCKER",
        "TASTATUR",
        "TABULATOR",
        "Lok",
        "Online",
        "Anz ge",
        "Komm rücks.",
        "abrufn",
        "Amerikanisch",
        "Finn",
        "Nied",
        "Norweg",
        "Span",
        "Portugiesisch",
        "Standard",
        "Fertig",
        "NÄCHSTE AUSWAHL",
        "80 Z",
        "132 Z",
        "umbruch",
        "darstellung",
        "Inv sdarstellung",
        "Strich",
        "Block",
        "F-T",
        "neue Zeile",
        "Bevorzugt",
        "DEC-MCS",
        "ISO-MCS",
        "64",
        "128",
        "lok",
        "Volle",
        "Nur national",
        "Nation",
        "+ Pseudografik",
        "Alle Z",
        "neue",
        "te neue Z",
        "bm.-Tastatur",
        "EDV",
        "Alle Buchstaben",
        "Kombiz",
        "Backspace",
        ",, und ..",
        "Sendet",
        "det `~",
        "det ESC",
        "setze Tab-"
    )
}
